<%@ Page Title="" Language="C#" MasterPageFile="~/admin/admin1.master" AutoEventWireup="true" CodeFile="Default.aspx.cs" Inherits="admin_Default" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <table class="nav-justified">
    <tr>
        <td>&nbsp;</td>
        <td style="text-align: center">
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="3" CellSpacing="5" DataKeyNames="s_num" DataSourceID="SqlDataSource1" EnableModelValidation="True">
                <Columns>
                    <asp:BoundField DataField="email" HeaderText="email" SortExpression="email" />
                    <asp:BoundField DataField="name" HeaderText="name" SortExpression="name" />
                    <asp:BoundField DataField="gender" HeaderText="gender" SortExpression="gender" />
                    <asp:BoundField DataField="contact" HeaderText="contact" SortExpression="contact" />
                    <asp:BoundField DataField="profilepic" HeaderText="profilepic" SortExpression="profilepic" />
                    <asp:BoundField DataField="x_yop" HeaderText="x_yop" SortExpression="x_yop" />
                    <asp:BoundField DataField="x_per" HeaderText="x_per" SortExpression="x_per" />
                    <asp:BoundField DataField="x_board" HeaderText="x_board" SortExpression="x_board" />
                    <asp:BoundField DataField="xii_yop" HeaderText="xii_yop" SortExpression="xii_yop" />
                    <asp:BoundField DataField="xii_per" HeaderText="xii_per" SortExpression="xii_per" />
                    <asp:BoundField DataField="xii_board" HeaderText="xii_board" SortExpression="xii_board" />
                    <asp:BoundField DataField="course" HeaderText="course" SortExpression="course" />
                    <asp:BoundField DataField="s_num" HeaderText="s_num" InsertVisible="False" ReadOnly="True" SortExpression="s_num" />
                </Columns>
                <EditRowStyle Font-Underline="False" HorizontalAlign="Center" VerticalAlign="Middle" />
                <EmptyDataTemplate>
                    email
                </EmptyDataTemplate>
                <FooterStyle BackColor="White" ForeColor="#000066" />
                <HeaderStyle BackColor="#006699" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="White" ForeColor="#000066" HorizontalAlign="Left" />
                <RowStyle ForeColor="#000066" />
                <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White" />
            </asp:GridView>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" DeleteCommand="DELETE FROM [registration] WHERE [s_num] = @s_num" InsertCommand="INSERT INTO [registration] ([email], [name], [gender], [contact], [profilepic], [x_yop], [x_per], [x_board], [xii_yop], [xii_per], [xii_board], [course]) VALUES (@email, @name, @gender, @contact, @profilepic, @x_yop, @x_per, @x_board, @xii_yop, @xii_per, @xii_board, @course)" SelectCommand="SELECT [email], [name], [gender], [contact], [profilepic], [x_yop], [x_per], [x_board], [xii_yop], [xii_per], [xii_board], [course], [s_num] FROM [registration]" UpdateCommand="UPDATE [registration] SET [email] = @email, [name] = @name, [gender] = @gender, [contact] = @contact, [profilepic] = @profilepic, [x_yop] = @x_yop, [x_per] = @x_per, [x_board] = @x_board, [xii_yop] = @xii_yop, [xii_per] = @xii_per, [xii_board] = @xii_board, [course] = @course WHERE [s_num] = @s_num">
                <DeleteParameters>
                    <asp:Parameter Name="s_num" Type="Int32" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="email" Type="String" />
                    <asp:Parameter Name="name" Type="String" />
                    <asp:Parameter Name="gender" Type="String" />
                    <asp:Parameter Name="contact" Type="String" />
                    <asp:Parameter Name="profilepic" Type="String" />
                    <asp:Parameter Name="x_yop" Type="String" />
                    <asp:Parameter Name="x_per" Type="String" />
                    <asp:Parameter Name="x_board" Type="String" />
                    <asp:Parameter Name="xii_yop" Type="String" />
                    <asp:Parameter Name="xii_per" Type="String" />
                    <asp:Parameter Name="xii_board" Type="String" />
                    <asp:Parameter Name="course" Type="String" />
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="email" Type="String" />
                    <asp:Parameter Name="name" Type="String" />
                    <asp:Parameter Name="gender" Type="String" />
                    <asp:Parameter Name="contact" Type="String" />
                    <asp:Parameter Name="profilepic" Type="String" />
                    <asp:Parameter Name="x_yop" Type="String" />
                    <asp:Parameter Name="x_per" Type="String" />
                    <asp:Parameter Name="x_board" Type="String" />
                    <asp:Parameter Name="xii_yop" Type="String" />
                    <asp:Parameter Name="xii_per" Type="String" />
                    <asp:Parameter Name="xii_board" Type="String" />
                    <asp:Parameter Name="course" Type="String" />
                    <asp:Parameter Name="s_num" Type="Int32" />
                </UpdateParameters>
            </asp:SqlDataSource>
        </td>
        <td>&nbsp;</td>
    </tr>
</table>
</asp:Content>

